### ISSUE TITLE
LINUX, YKUSH not working anymore

### ISSUE THREAD

**Issue by biboc** [Yepkit/ykush#9]
Hi, 
I've downloaded the repo (Commit: ee136bda1c406ba7360220ef426f0b200df566d6) and I'm on Ubuntu 16.04
I'm not able to manage my YKUSH device, I can detect it with ykushcmd -l but I can't control the device plugged.

I found one error in parsing the arguments: https://github.com/Yepkit/ykush/blob/master/ykushcmd/ykush/ykush.cpp#L67
You're looking for at least 6 arguments but command line is:
`ykushcmd -s SERIAL -u 3`
which is 5 arguments
Please explain me or correct the bug

Another problem, on this same version, you set his to blocking mode `hid_set_nonblocking(handle, 0);` . This command never ends on my Ubuntu 16.04. Using non-blocking mode make YKUSH to work as expected

**Comment by yep1** [comment]
Hi,
thanks for the identifying this issue.

There was in fact, as you pointed, an error on the command parsing method. We just corrected and added a new commit to eliminate this bug.

On the other point, in spite of using the blocking option the command should return after receiving the command execution confirmation from the board. We prefer the blocking option to get confirmation of command execution on the board side. Nonetheless it will have that effect of "never" ending if the host is not receiving feedback from the board.

We will evaluate adding a timeout and printing a message to the user instead of waiting indefinitely.

Best Regards
